from django.urls import path
from .views import (
    CategoriaListView,
    CategoriaDetailView,
    CategoriaCreateView,
    CategoriaUpdateView,
    CategoriaDeleteView,
    ContactosListView,
    ContactosDetailView,
    ContactosCreateView,
    ContactosUpdateView,
    ContactosDeleteView,
    PedidosListView,
    PedidosDetailView,
    PedidosCreateView,
    PedidosUpdateView,
    PedidosDeleteView,
    ProductosListView,
    ProductosDetailView,
    ProductosCreateView,
    ProductosUpdateView,
    ProductosDeleteView,
    UsuariosListView,
    UsuariosDetailView,
    UsuariosCreateView,
    UsuariosUpdateView,
    UsuariosDeleteView,
    RolesListView,
    RolesDetailView,
    RolesCreateView,
    RolesUpdateView,
    RolesDeleteView,
    PerfilesListView,
    PerfilesDetailView,
    PerfilesCreateView,
    PerfilesUpdateView,
    PerfilesDeleteView,
    PerfilPermisosUpdateView,
    SexosListView,
    SexosDetailView,
    SexosCreateView,
    SexosUpdateView,
    SexosDeleteView,
    EstadoPedidosListView,
    EstadoPedidosDetailView,
    EstadoPedidosCreateView,
    EstadoPedidosUpdateView,
    EstadoPedidosDeleteView,
    ConfigContactoListView,
    ConfigContactoDetailView,
    ConfigContactoCreateView,
    ConfigContactoUpdateView,
    ConfigContactoDeleteView,
    PedidoProductoUpdateFormView,
    ProductosAuditoriaView,
    ConsultasDinamicasCreateView,
    ConsultasDinamicasDeleteView,
    ConsultasDinamicasDetailView,
    ConsultasDinamicasListView,
    ConsultasDinamicasUpdateView,
    reporte_view,
    # logout_view,
    # login_view,
    # register_view,
    admin_home,
    # Panel de Control
    panel_dashboard,
    panel_productos_list,
    panel_productos_crear,
    panel_productos_editar,
    panel_productos_detail,
    panel_productos_eliminar,
    toggle_producto_hidden,
    panel_usuarios_list,
    panel_usuarios_crear,
    panel_usuarios_editar,
    panel_usuarios_detail,
    panel_pedidos_detail,
    panel_pedidos_cambiar_estado,
    panel_pedidos_list,
    panel_categorias_list,
    panel_categorias_crear,
    panel_categorias_editar,
    panel_roles_list,
    panel_perfiles_list,
    panel_sexos_list,
    panel_estados_list,
    panel_consultas_list,
    panel_toggle_guest_checkout,
    panel_auditoria,
    panel_reportes,
)

urlpatterns = [

    

    path('', admin_home, name='admin_home'),


    path('categorias/', CategoriaListView.as_view(), name='categoria_list'),
    path('categorias/<str:pk>/detalle/', CategoriaDetailView.as_view(), name='categoria_detail'),
    path('categorias/crear/', CategoriaCreateView, name='categoria_create'),
    path('categorias/<str:pk>/editar/', CategoriaUpdateView, name='categoria_update'),
    path('categorias/<str:pk>/eliminar/', CategoriaDeleteView.as_view(), name='categoria_delete'),

    path('contactos/', ContactosListView.as_view(), name='contactos_list'),
    path('contactos/<int:pk>/', ContactosDetailView.as_view(), name='contactos_detail'),
    path('contactos/crear/', ContactosCreateView, name='contactos_create'),
    path('contactos/<int:pk>/editar/', ContactosUpdateView, name='contactos_update'),
    path('contactos/<int:pk>/eliminar/', ContactosDeleteView, name='contactos_delete'),

    path('pedidos/', PedidosListView.as_view(), name='pedidos_list'),
    path('pedidos/<int:pk>/', PedidosDetailView.as_view(), name='pedidos_detail'),
    path('pedidos/crear/', PedidosCreateView, name='pedidos_create'),
    path('pedidos/<int:pk>/editar/', PedidosUpdateView, name='pedidos_update'),
    path('pedidos/<int:pk>/eliminar/', PedidosDeleteView, name='pedidos_delete'),


    path('productos/', ProductosListView.as_view(), name='productos_list'),
    path('productos/<str:pk>/detalle/', ProductosDetailView.as_view(), name='productos_detail'),
    path('productos/crear/', ProductosCreateView, name='productos_create'),
    path('productos/<str:pk>/editar/', ProductosUpdateView, name='productos_update'),
    path('productos/<str:pk>/eliminar/', ProductosDeleteView.as_view(), name='productos_delete'),
    path('productos/<str:pk>/toggle-oculto/', toggle_producto_hidden, name='productos_toggle_hidden'),

    path('productos_auditoria/', ProductosAuditoriaView, name='productos_auditoria'),

    path('usuarios/', UsuariosListView.as_view(), name='usuarios_list'),
    path('usuarios/<str:pk>/detalle/', UsuariosDetailView.as_view(), name='usuarios_detail'),
    path('usuarios/crear/', UsuariosCreateView, name='usuarios_create'),
    path('usuarios/<str:pk>/editar/', UsuariosUpdateView, name='usuarios_update'),
    path('usuarios/<str:pk>/eliminar/', UsuariosDeleteView, name='usuarios_delete'),


    path('roles/', RolesListView.as_view(), name='roles_list'),
    path('roles/<int:pk>/', RolesDetailView.as_view(), name='roles_detail'),
    path('roles/crear/', RolesCreateView, name='roles_create'),
    path('roles/<int:pk>/editar/', RolesUpdateView, name='roles_update'),
    path('roles/<int:pk>/eliminar/', RolesDeleteView.as_view(), name='roles_delete'),

    path('perfiles/', PerfilesListView.as_view(), name='perfiles_list'),
    path('perfiles/<int:pk>/', PerfilesDetailView.as_view(), name='perfiles_detail'),
    path('perfiles/crear/', PerfilesCreateView, name='perfiles_create'),
    path('perfiles/<int:pk>/editar/', PerfilesUpdateView, name='perfiles_update'),
    path('perfiles/<int:pk>/eliminar/', PerfilesDeleteView.as_view(), name='perfiles_delete'),
    path('perfiles_permisos/<int:pk>/editar/', PerfilPermisosUpdateView, name='perfil_permisos_update'),

    path('sexos/', SexosListView.as_view(), name='sexos_list'),
    path('sexos/<int:pk>/', SexosDetailView.as_view(), name='sexos_detail'),
    path('sexos/crear/', SexosCreateView.as_view(), name='sexos_create'),
    path('sexos/<int:pk>/editar/', SexosUpdateView.as_view(), name='sexos_update'),
    path('sexos/<int:pk>/eliminar/', SexosDeleteView.as_view(), name='sexos_delete'),

    path('estado_pedidos/', EstadoPedidosListView.as_view(), name='estado_pedidos_list'),
    path('estado_pedidos/<int:pk>/', EstadoPedidosDetailView.as_view(), name='estado_pedidos_detail'),
    path('estado_pedidos/crear/', EstadoPedidosCreateView.as_view(), name='estado_pedidos_create'),
    path('estado_pedidos/<int:pk>/editar/', EstadoPedidosUpdateView.as_view(), name='estado_pedidos_update'),
    path('estado_pedidos/<int:pk>/eliminar/', EstadoPedidosDeleteView.as_view(), name='estado_pedidos_delete'),

    path('config_contacto/', ConfigContactoListView.as_view(), name='config_contacto_list'),
    path('config_contacto/<int:pk>/', ConfigContactoDetailView.as_view(), name='config_contacto_detail'),
    path('config_contacto/crear/', ConfigContactoCreateView, name='config_contacto_create'),
    path('config_contacto/<int:pk>/editar/', ConfigContactoUpdateView.as_view(), name='config_contacto_update'),
    path('config_contacto/<int:pk>/eliminar/', ConfigContactoDeleteView.as_view(), name='config_contacto_delete'),

    path('pedidos/<int:ped_id>/producto/<str:prod_id>/editar/', PedidoProductoUpdateFormView, name='pedido_producto_update'),


    path('consultas_dinamicas/', ConsultasDinamicasListView.as_view(), name='consultas_dinamicas_list'),
    path('consultas_dinamicas/<int:pk>/', ConsultasDinamicasDetailView.as_view(), name='consultas_dinamicas_detail'),
    path('consultas_dinamicas/crear/', ConsultasDinamicasCreateView, name='consultas_dinamicas_create'),
    path('consultas_dinamicas/<int:pk>/editar/', ConsultasDinamicasUpdateView.as_view(), name='consultas_dinamicas_update'),
    path('consultas_dinamicas/<int:pk>/eliminar/', ConsultasDinamicasDeleteView.as_view(), name='consultas_dinamicas_delete'),

    path('consultas_dinamicas/reporte/<int:id>/', reporte_view, name='consultas_dinamicas_reporte'),

    # ─── Panel de Control (visor dark, capa aparte) ───
    path('panel/', panel_dashboard, name='panel_dashboard'),
    path('panel/productos/', panel_productos_list, name='panel_productos'),
    path('panel/productos/crear/', panel_productos_crear, name='panel_productos_crear'),
    path('panel/productos/<str:pk>/editar/', panel_productos_editar, name='panel_productos_editar'),
    path('panel/productos/<str:pk>/toggle-oculto/', toggle_producto_hidden, name='panel_productos_toggle_hidden'),
    path('panel/productos/<str:pk>/detalle/', panel_productos_detail, name='panel_productos_detalle'),
    path('panel/productos/<str:pk>/eliminar/', panel_productos_eliminar, name='panel_productos_eliminar'),
    path('panel/usuarios/', panel_usuarios_list, name='panel_usuarios'),
    path('panel/usuarios/crear/', panel_usuarios_crear, name='panel_usuarios_crear'),
    path('panel/usuarios/<str:pk>/editar/', panel_usuarios_editar, name='panel_usuarios_editar'),
    path('panel/usuarios/<str:pk>/detalle/', panel_usuarios_detail, name='panel_usuarios_detalle'),
    path('panel/pedidos/', panel_pedidos_list, name='panel_pedidos'),
    path('panel/pedidos/<int:pk>/detalle/', panel_pedidos_detail, name='panel_pedidos_detalle'),
    path('panel/pedidos/<int:pk>/cambiar-estado/', panel_pedidos_cambiar_estado, name='panel_pedidos_cambiar_estado'),
    path('panel/categorias/', panel_categorias_list, name='panel_categorias'),
    path('panel/categorias/crear/', panel_categorias_crear, name='panel_categorias_crear'),
    path('panel/categorias/<str:pk>/editar/', panel_categorias_editar, name='panel_categorias_editar'),
    path('panel/roles/', panel_roles_list, name='panel_roles'),
    path('panel/perfiles/', panel_perfiles_list, name='panel_perfiles'),
    path('panel/sexos/', panel_sexos_list, name='panel_sexos'),
    path('panel/estados/', panel_estados_list, name='panel_estados'),
    path('panel/consultas/', panel_consultas_list, name='panel_consultas'),
    path('panel/toggle-guest-checkout/', panel_toggle_guest_checkout, name='panel_toggle_guest_checkout'),
    path('panel/auditoria/', panel_auditoria, name='panel_auditoria'),
    path('panel/reportes/', panel_reportes, name='panel_reportes'),
]
